dist: trusty
sudo: false
language: python
python: 3.6
cache:
  apt: true
  pip: true
install:
  - pip install -U pip
  - pip install cython
  - pip install -U ucca
  - python -m spacy download en_core_web_md
  - python -m spacy download de_core_news_md
env:
  global:
    - SCRIPTS=https://raw.githubusercontent.com/UniversalConceptualCognitiveAnnotation/docs/master/scripts
    - secure: "XQ/QyaVW/J2pDdG7aTGLn3rVGlAFkNNYRwfjLQR4Bk9OFOn0rKhGNqDgbWc/VBINtpvTqfeg/jS1lF08BdSbOBUOO5DqpjzWUAyZucJm0w7lpu4st1DSE4cACtZYL2WGPYbV84rDGyCEodhIXqoU8WjCsp+JYiF8UoMwPD3NfLCKKxS391b2Wd92DPrukBOHu+knPSErje1+3iBQSsSgalQfRLVtIApHHAy3GI0yDVhG10f/EOPb+iGxDNlQL02n3BX6Cuds065cadm7UAMuwV0YqG/DBNao+0dKJ1NpTqaLoxaB62muNUjtfranwwJCz7FW7SbhexTOWJo7KBLcq1e3MYLZWlgUMdG1w027olO55EffotXsp5JJg/NyONUjrXxsHVqCGRmwur10sF+qwqmoGOcIgHLsyaw8WFLR4Dtlgtcc2BAa5vGYOttpxpHS6DaI2+ku3odWSBC2C5jMdanZnZx6cmn2bVZyM5z+m/bjrXNwdz0GeMIpjDZmhfCQtGesffFmqhgLyWIxGTXzha0XnqD87opxfk+XU/I3iFb6VFTd1WZSymeLYrZr7X8KW8n/pV6UhmN7H6FJ8Bluk6qeWSGnvJeBISLJ2Guk7h8tyTFeU4kEpQsR5GsbP27peCicNiawKMzPXRH4uQPd8d+YSAAjAN8oxbekx2/+l0Y="
jobs:
  include:
    - script: python -m scripts.validate xml --no-linkage
    - stage: split
      script:
        - curl $SCRIPTS/split_to_sentences.sh | bash
        - git rm -f 25515002.pickle  # Too long - 386 tokens
    - stage: convert
      script: curl $SCRIPTS/validate_sentences.sh | bash -s -- --no-linkage
      env: FORMAT=validate
    - script: curl $SCRIPTS/sentences_to_xml.sh | bash
      env: FORMAT=xml
    - script: curl $SCRIPTS/tupa.sh | bash
      env: FORMAT=tupa
    - script: curl $SCRIPTS/visualize.sh | bash -s "250"
      env: FORMAT=visualize
    - script: curl $SCRIPTS/visualize.sh | bash -s "254"
      env: FORMAT=visualize
    - script: curl $SCRIPTS/visualize.sh | bash -s "255"
      env: FORMAT=visualize
    - script: curl $SCRIPTS/visualize.sh | bash -s "256[0-4]"
      env: FORMAT=visualize
    - script: curl $SCRIPTS/visualize.sh | bash -s "256[5-9]"
      env: FORMAT=visualize
    - script: curl $SCRIPTS/visualize.sh | bash -s "257[0-4]"
      env: FORMAT=visualize
    - script: curl $SCRIPTS/visualize.sh | bash -s "257[5-9]"
      env: FORMAT=visualize
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=sdp
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=conll
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=conllu
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT "250"
      env: FORMAT=amr
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT "254"
      env: FORMAT=amr
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT "255"
      env: FORMAT=amr
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT "256"
      env: FORMAT=amr
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT "257"
      env: FORMAT=amr
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=export
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=txt
    - stage: evaluate
      script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=sdp
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=conll
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=conllu
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT "250"
      env: FORMAT=amr
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT "254"
      env: FORMAT=amr
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT "255"
      env: FORMAT=amr
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT "256"
      env: FORMAT=amr
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT "257"
      env: FORMAT=amr
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=export
after_success: curl $SCRIPTS/push.sh | bash

